---
- name: install Flaskex to Ubuntu 18.04
  hosts: webservers
  remote_user: client
  become: True
  tasks:
  - name: install pip3
    apt: 
      name: python3-pip
      update_cache: yes 
  - name: install git
    apt: 
      name: git
      update_cache: yes 
  - name: pull app from github
    git:
      repo: https://github.com/anfederico/flaskex.git 
      dest: /home/client/Рабочий стол/app
  - name: install requirements 
    pip:
      requirements:
        '/home/client/Рабочий стол/app/requirements.txt'
  - name: downgrade WTForms library
    pip:
      name: WTForms
      state: absent
  - name: install WTForms to version 2.3.3
    pip:
      name: WTForms
      version: 2.3.3

